# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

r:
  - oldrel
  - release
  - devel
cache: packages

r_github_packages:
  - r-lib/covr
before_cache: Rscript -e 'remotes::install_cran("pkgdown")'

after_success:
  - Rscript -e 'covr::codecov(line_exclusions = "R/uniqID_maker_addin.R")'